### ISSUE TITLE
Локальные яку

### ISSUE THREAD

**Issue by WarL0ckNet** [MahjongPantheon/Mimir#84]
На развитие: возможно сделать конструктор правил клуба где будут описано использование локальных  яку. Предлагаю список из книги http://dora.ucoz.net/ (стр. 624) там всего 24 шт.
Для начала выбрать наиболее интересные:
- Open riichi
- Isshoku sanjun (Три идентичных чи одной масти)
- Sanrenkou (три последовательных пона)
- Isshoku yonjun (четыре идентичных чи)
- Dai sharin (великая колесница)
- suurenkou (четыре последовательных пона)

**Comment by ctizen** [comment]
https://pantheon.myjetbrains.com/youtrack/issue/MIMIR-28
